name: Deploy on Self-Hosted

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy the app
              run: |
                  cd /home/ubuntu/projects/elira-backend
                  pm2 stop 0
                  git pull origin main
                  rm -rf ./node_modules
                  npm install
                  npx nest build
                  pm2 restart 0
